version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Europe/Berlin
  labels:
  - type > dependency
  - type > automated
  rebase-strategy: disabled
